<a href="https://colab.research.google.com/github/Jaganjagan05/Deep-Learning-project/blob/main/improving_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np


In [9]:
x=np.arange(-50,70,3)
y=np.arange(-40,40,2)
x

array([-50, -47, -44, -41, -38, -35, -32, -29, -26, -23, -20, -17, -14,
       -11,  -8,  -5,  -2,   1,   4,   7,  10,  13,  16,  19,  22,  25,
        28,  31,  34,  37,  40,  43,  46,  49,  52,  55,  58,  61,  64,
        67])

In [10]:
y

array([-40, -38, -36, -34, -32, -30, -28, -26, -24, -22, -20, -18, -16,
       -14, -12, -10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8,  10,
        12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,  36,
        38])

In [13]:
tf.random.set_seed(42)
model=tf.keras.Sequential(
    [tf.keras.layers.Dense(units=1,input_shape=[1])
    ])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [12]:
model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.SGD(),
              metrics=['mae'])

In [15]:
model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.SGD(),
              metrics=['mae'])


In [16]:
model.fit(tf.expand_dims(x,axis=-1),y,epochs=5)

Epoch 1/5
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 28.4827 - mae: 28.4827
Epoch 2/5
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 11.1150 - mae: 11.1150
Epoch 3/5
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 6.8324 - mae: 6.8324
Epoch 4/5
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 6.0975 - mae: 6.0975
Epoch 5/5
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 5.8478 - mae: 5.8478


In [23]:
x

array([-50, -47, -44, -41, -38, -35, -32, -29, -26, -23, -20, -17, -14,
       -11,  -8,  -5,  -2,   1,   4,   7,  10,  13,  16,  19,  22,  25,
        28,  31,  34,  37,  40,  43,  46,  49,  52,  55,  58,  61,  64,
        67])

In [24]:
y

array([-40, -38, -36, -34, -32, -30, -28, -26, -24, -22, -20, -18, -16,
       -14, -12, -10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8,  10,
        12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,  36,
        38])

In [22]:
model.predict(np.array([70]))  ### the answer should be 40 but here it showing 44 so we have to improve our model

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step


array([[44.666588]], dtype=float32)

In [25]:
model.fit(tf.expand_dims(x,axis=-1),y,epochs=100)

Epoch 1/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 6.2767 - mae: 6.2767
Epoch 2/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 7.0788 - mae: 7.0788
Epoch 3/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 6.0800 - mae: 6.0800
Epoch 4/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 5.8226 - mae: 5.8226
Epoch 5/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 6.2689 - mae: 6.2689
Epoch 6/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 6.8942 - mae: 6.8942
Epoch 7/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 5.9181 - mae: 5.9181
Epoch 8/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 5.6399 - mae: 5.6399
Epoch 9/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 6.8934 - mae: 6.8934
Epoch 10/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 6.0135 - mae: 6.0135
Epoch 11/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 5.7502 - mae: 5.7502
Epoch 12/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 6.2105 - mae: 6.2105
Epoch 13/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/ste

In [37]:
model.predict(np.array([70]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step


array([[38.986378]], dtype=float32)

In [42]:
tf.random.set_seed(42)
model=tf.keras.Sequential([tf.keras.layers.Dense(units=10,input_shape=[1]),
    tf.keras.layers.Dense(100,activation='relu'),
    tf.keras.layers.Dense(100,activation='relu'),
    tf.keras.layers.Dense(100,activation='relu'),
    tf.keras.layers.Dense(100,activation='relu'),


    tf.keras.layers.Dense(1)
    ])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [43]:
model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.Adam(),
              metrics=['mae'])

In [47]:
model.fit(tf.expand_dims(x,axis=-1),y,epochs=100)

Epoch 1/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 3.0302 - mae: 3.0302
Epoch 2/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 2.7339 - mae: 2.7339
Epoch 3/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 3.2476 - mae: 3.2476
Epoch 4/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 3.0296 - mae: 3.0296
Epoch 5/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 2.6817 - mae: 2.6817
Epoch 6/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 2.7229 - mae: 2.7229
Epoch 7/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 2.9094 - mae: 2.9094
Epoch 8/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 2.8394 - mae: 2.8394
Epoch 9/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 2.6597 - mae: 2.6597
Epoch 10/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 2.5924 - mae: 2.5924
Epoch 11/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 2.7085 - mae: 2.7085
Epoch 12/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 2.8448 - mae: 2.8448
Epoch 13/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/ste

In [48]:
model.predict(np.array([70]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step


array([[38.89114]], dtype=float32)